apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:q8gBYxI=,iv:heTDelZRmo0FxhQd0w8MX0n8HaWwu1j+9D1GkJMviv0=,tag:KfCIwVHycvLbrNWc869Pxw==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:WNFMvR2BMfyZx/sNh+BNJei41tGCc6rL0e4=,iv:prPKx/MrtUYg2Vg2u9kCRZMnncwW5loDbCGZD9U6grA=,tag:Je3cRVuL8K3gGgZnH8cj9g==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNTg5RExCWlhRMEFIYTRX
            Ny9mRDV4a0QrWVJsU3pTZTBjUjlRNm0xNWhRCkI5ZU45Y2NqWnR6b29kYzVtaC9E
            eEtITkhWb2lzMG1zaTdhT1l0YTYwcUEKLS0tIGxsclFFbk1kNVUrV1crU21UandE
            eUNYK29OSkpuRUNadUQzK2Z4Q2dqQXMKhh3HpQ/h4Rp8fsmhw5bMC4BKk2npGT21
            AfJvqmwIb6xMs0Z0s5Go0rN7A3Iwzg2uBER6XKA/oWESsqn7AVMQ5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T05:22:45Z"
    mac: ENC[AES256_GCM,data:5BkganN7AOID04dtnZqJcCM5Y855U9qbiIdWnA+BxG8UBkGv7GMr9fYNmJlb0T1GQzMcAP8YXXkurZ0C7oswGU9L45UjezOWdxMZGKrwFnSq7BYo/vRrygFFoaouAbAdxnl9sBtTa4EVF4W1rzudXuuXPz1IBHHBg3S9CdTSjAI=,iv:XyqCaa9vMEwlexyZOWCL/2uN3c+lKBnJwGEk/MMW9ms=,tag:dKNYmmXPrY3rVS/A1kxUiA==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
