apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage
spec:
  configuration:
    destinationPath: s3://cnpg/
    endpointURL: "${GARAGE_ENDPOINT_URL}"
    s3Credentials:
      accessKeyId:
        name: garage-cnpg
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: garage-cnpg
        key: SECRET_ACCESS_KEY
    wal:
      compression: zstd
      maxParallel: 8
    data:
      compression: gzip
  retentionPolicy: 15d
