apiVersion: v1
kind: Secret
metadata:
    name: garage-cnpg
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:++yeMTlQBIkc8IArxBenzhi02rVsFeQun5U=,iv:UFqmFupZB1BFwh4hVTZRdDFIyesoFQA/56PyHg3e3JE=,tag:R23//1skWrDtnbvdQkoFjg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:J9mYaWk8dWf0SD/XkB3l0Mh/JljvzknHn1JUWYY5irdeh6IFvDV0BysfxbmMI744jHR//yA6gT4BMly1Wcpn4Q==,iv:6RLFcsiyDa5/eaEaGlSxNGZlsnU/HgVDRxmqjIZG1Ow=,tag:ITDebp1Kd6mJfvOGqWzzAA==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VUJ4US82MlM0cUR4SkMy
            cHlDTC9CNTlQR1ZTUHlUU2dvZ2tDMXRmVlI4CitXUGhpcHh3WDBNdmovc2IvZzNx
            aCtLODRudU9PazFncU12NjRQVXh6WjQKLS0tIEs4VVN0N3NLYis1OFFEVldoVzE5
            RmdqNjNyYlNCMmlNUlhrV2xKYTFzMEEK+A0RKMRpqAdIgO5Oa/0BH5uzlhEDXdke
            A4YLDPZ1OGzPxaE2sCl2UsoBvL5Lvp7FSt5ZC4o3zs6+FtQTW4x9og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T21:53:32Z"
    mac: ENC[AES256_GCM,data:I/28UICsE4aQDgvcdlr+kColZvbjuIZS0X2AAn0nDC9MYp6kFe2bZiEvoQBDOe4CMo0JKAzGtsiR63nvyCa3mOpIpb1PoVY1h6BLfOosnnOXeIGAofS+LoYevwQ2/ocxiW3dgeZiUhkdpfV5T4eNMkuHW+63S55EomkGA609WZg=,iv:59wqBXVT7vuvmZaAahKTP9+a+EulCfhxfYP/QIcFua8=,tag:aWoXtkMGCNEpYhH0VM4Ogg==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
