---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-operator
  interval: 1h
  values:
    operator:
      enable_converter_ownership: true
    env:
      # required for the operator to create HTTPRoutes specified on CRs
      - name: VM_GATEWAY_API_ENABLED
        value: "true"
    serviceMonitor:
      enabled: true
    crds:
      enabled: true
      plain: true
