apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:67yBsRO3gxgrtXIwXasyU1z2la5dGFEYGiGXExo6ZI06LDYytQRl2Q==,iv:ZZ4Ncl6BdukaeTwBCB5BOneJw9P2Z1jGLtCteiNzFZU=,tag:ADFipKO0i3RPsi+/I2Skfw==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxN2FsV09zWFZOSWdzdCtk
            cnNiSUw3bDFBdktJdDc4VVRkNDRKZ1k5WVh3Ci94SGtaczJmZmU2aGdPK1lpSVc1
            RjkyUUsyVlFrRUQxYmZhOWdpRXcwcmcKLS0tIGcxalRaUVNZbG15ckpzZ2hqZ3hH
            UmlwYUlVcU9WRmtLaVg3TXRvdUh3WUUKR7WdJvmHkpHQo2HqTi52YhVCcdEULxQj
            4wtlaK1c+dBvMlruFH6aiThHbrIjO+DG/y+JaZ1N60SeaUbOWqSxFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T06:48:42Z"
    mac: ENC[AES256_GCM,data:Ghd0L5ECRdT6PCa4EiHFz0oJUkL8mlRGGex0A0QbGQ5j6vp7K5ZohIYYwPJBf1oXwUZS2wzrFUfDKo72Dd6grujNFnBXWyJSWB8ybQD7eKVLrB+5gwVWd2cmEyndrdFiQcjH/EYZDIqqmxxo3su5/ANT96zPvvxmsHzqPypTVfE=,iv:+xEIW4kKMBnjemh1G0EazrDnGKouZbEf21t3H0q0Bwc=,tag:c/XG82k/W2l72om4N/B/jg==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
