apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:T8VqLktFLVGnhoIe16tMQ7jN,iv:LmGvyyidCzAJwMJX0d8KY0QeCmEsKq72eUX76IjFtjk=,tag:YvnrVyx/2xsNW5hnzBQ+3A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:TxrR5m0GGCWNqbY0tg0XWHiGARXpzAFTnN0kOK9Fm1uzR4ctoAfwfJ6BFu/m/c/Na8PfAZ0otc2PBKvMK5pgjg==,iv:9ocdRhVs0lCL32vRHIOF1oLYD64/+C5S1t1Cx3bkS9A=,tag:R+MVci1wXFL0L4sfmgemGA==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtT0c4WG5HYXNIUEtqZWVZ
            TVRKcUx3dVpkRDRoZDdSeDJLM25DYmdmL1NFCmlFWHVqbjh4UFNtNzVja2tIanM4
            N2tDaG9TUlF2RFVNYWpYL3V1VnR0TDAKLS0tIEYzcGUzQmMyZytBVkpaY3pGWFBa
            Vk1KcVpXSjlEa3lwTWR6ZDA5Z0dKOVEKwkZ86OmcS5si4PGkwqEds3kT6BIXMJ+u
            gL9sph5Oduf/dNaq0jYJGaN3sPLeqBsznWgqkBAOStIfs+6V3f40JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T04:06:51Z"
    mac: ENC[AES256_GCM,data:An6Z7LJYKFmOiu9HkYvz9nXFAIZ4t+0d0rEqylLqiLqLbfBUwH4iRNMKtpwfRMNT2aKpdIswOwL69+WDyyw7R/7hI87QU9NPKq8MorNwadb2dbMhzHzWJM+rca89LYhnEHz2rzVsQnNygk2sXjYv6vcGLJLPDF87TO7xZBaiZ30=,iv:VB4i0o8V+nixuRDD0f8IY/Fu66AWyQVY+xhqzUc6krA=,tag:7LsaE9+GAPRcRTC44dx53A==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
