apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:0mGqUffZk4+QDr62M0/H,iv:4ixBY7JoArhUB3WI+0AhsNYRnm8NlCeqv8Ikb9F/pRM=,tag:1QgC90TBvuCTU6MXmUd1xg==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VSuEJJojtgQKq+33yCeD2puImzKgJY/oejfh9WNDPklAY4S3,iv:fSH+lXkRXDCSOancg4AfQGvKR0IYs/m75gXII1VIcv0=,tag:QmXgzRGNC1d/A0vhUgHwFg==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTXQrVWhrYm10b0grVHlm
            N0FxVDN3Ry9zZlYxKzJkclRXZ0xoVVZlWTNrCnBibERpeHEzTW4wMWJwR0Q4ckR5
            YWNSTzd2S3VCeHdkNWZXY2ZJT1I5bDAKLS0tIDhDdHJaNHhYVUlJWnp6c0xIUXAv
            ck15cnJhZjYzWTRZU1g3RzJhODlhdVEKqTuY2q5nOZh47ntzMIqpcEQz7pjQ3PPM
            W2Qle6Vt8OJpob9TRQ5f11l1vAkmKWEEYOpflglSlBR23L5lRgVU3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T05:14:19Z"
    mac: ENC[AES256_GCM,data:wwfvmFp5zENEYatwPswBEcKRUzzWaFYU/lifor4+Geudpq4OdRzUQJ12Dd5psPKex6ffBuRMbn1JYoAWI5DE0avFCPKktleba0hwJBWjVfjO84V3i0jQSw7q7Bf3YDcZ0ztd9KvsQqjkDiH5SmXjI0b2Vzgo0LvMBirxY07gxwk=,iv:AxLy/mHV9HggAPD+vEjfuWdaMMaMuU4+tmW0cUEBBeg=,tag:umdKDrkniDPpvyUDl8K4sA==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
