apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData: {}
sops:
  age:
    - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTXQrVWhrYm10b0grVHlm
        N0FxVDN3Ry9zZlYxKzJkclRXZ0xoVVZlWTNrCnBibERpeHEzTW4wMWJwR0Q4ckR5
        YWNSTzd2S3VCeHdkNWZXY2ZJT1I5bDAKLS0tIDhDdHJaNHhYVUlJWnp6c0xIUXAv
        ck15cnJhZjYzWTRZU1g3RzJhODlhdVEKqTuY2q5nOZh47ntzMIqpcEQz7pjQ3PPM
        W2Qle6Vt8OJpob9TRQ5f11l1vAkmKWEEYOpflglSlBR23L5lRgVU3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T02:46:18Z"
  mac: ENC[AES256_GCM,data:4qVIFRrv2FNZrrDiaDTMPiWzGMZX0YxT2aQN85Af7oS9RfVqj6p2dW44Kjlf4WBHkYbUfm1uhFp9pBO+XNLVcsHQNAGuXjMIm6MMbYBFgzYy9izyocsPjzhcOyo/503CH6iGm0Y4Xq9bJvpFHii/v++0R7YTV6g6n5ApzDuUtwI=,iv:PESz+rgDtEoNSNtiI2/QZxONdlFb+bIrhtMOUWvbpWM=,tag:tfoLxDWVM8K70HKljAVrgQ==,type:str]
  encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
  mac_only_encrypted: true
  version: 3.11.0
