apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:0mGqUffZk4+QDr62M0/H,iv:4ixBY7JoArhUB3WI+0AhsNYRnm8NlCeqv8Ikb9F/pRM=,tag:1QgC90TBvuCTU6MXmUd1xg==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTXQrVWhrYm10b0grVHlm
            N0FxVDN3Ry9zZlYxKzJkclRXZ0xoVVZlWTNrCnBibERpeHEzTW4wMWJwR0Q4ckR5
            YWNSTzd2S3VCeHdkNWZXY2ZJT1I5bDAKLS0tIDhDdHJaNHhYVUlJWnp6c0xIUXAv
            ck15cnJhZjYzWTRZU1g3RzJhODlhdVEKqTuY2q5nOZh47ntzMIqpcEQz7pjQ3PPM
            W2Qle6Vt8OJpob9TRQ5f11l1vAkmKWEEYOpflglSlBR23L5lRgVU3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T17:59:05Z"
    mac: ENC[AES256_GCM,data:142Ei9GJ4jHrRaxR3erlVieaDuUEOwZpBhVGMZQE/jfwE9HtH2GbnocSGxtb3Ww62W/Zso4nwE7cyJeqL1G4SUSk31LNmpJCLqij9E4cdQikQr397b/XmN/T33bRwrbZmncPQFPbN17oLz84N9EVAQkU9IqAgWX27BKyqYZyTo8=,iv:1K6dC+1WVczsrIdJAvSPsn/adr/87rMcPTvhb7ODTY8=,tag:vR/cbDgoDMthXfp/VxgiAA==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
