apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-api-token
stringData:
    token: ENC[AES256_GCM,data:k7ezZwhhtsT7jjSbjI7V3nhsdG+qpH+zlap22hgZ5Jd+MKBzd2oqMH43ezQfuDwVicTZFq4y4n0G2VZgL61BtgNAjJHjCcTWDloYcjsw799ZeyES0+M8AhDQ1zo1IicWJUw+5YE0HLXLX9dD9PPFOzT3Pju8Zr+iQztEYgAvJqdDalQmQPxZbJkfEJ3hH4atI8tji3n4mCn5AyPM6xuLGbMgjCzhfyqX3Y9ZbPnk/yYHsb24vwfk,iv:ilXryTyuyKWjJE7T42nRN1nNkWrJwsYnHq95YuLlAo0=,tag:C/uphZ+6Rf/axuAdKjednw==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK25XOGU1SmF5bXVLTERQ
            UndINHJ4enR1b1NRM2ErSEFocXZsZ2ROS213ClVlQWJkaUVVeGd1WDVQUlB2NWdu
            V0ZndTRQLzdsOXpTZlpZK2FTb0dOTE0KLS0tIE5jTTlNdXBjWXNiK20wS3dWWnlU
            MkVNVXZiaUQ4MFc2TGVleHBZb25UTzQK9/bpVUADxn3n2lpsG1ty9L0IGMqx9mbK
            fJEpsmyCyRoTmtlswr4nkK+t/SZF6Vmn49GSO5qYpXzNwtuTm10ekA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T03:50:37Z"
    mac: ENC[AES256_GCM,data:a6d+JdaJt/3eB2kfwJESBhfGd52dKFzLBtFF7GEOZvUgfFEHFiBIuebV30t01c3ao8uFvkj0/O6fWmFt3dTGY9TL1zZVq0zAgftP4CpLcq35Q9a9iYxyCfwCY+WjYAmoS2DjKLf8IPeavp8nyZMG/sB1b0VRc5WuzR+YXsIV5Jo=,iv:MtGO/PJ+GkayyjoQ+FoGOfy5Y8j0UkiRR7ACu9dYSpY=,tag:1JBAdNLXcg2Rm5xlYa/cmg==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
