apiVersion: v1
kind: Secret
metadata:
    name: homeassistant-token
stringData:
    token: ENC[AES256_GCM,data:k7ezZwhhtsT7jjSbjI7V3nhsdG+qpH+zlap22hgZ5Jd+MKBzd2oqMH43ezQfuDwVicTZFq4y4n0G2VZgL61BtgNAjJHjCcTWDloYcjsw799ZeyES0+M8AhDQ1zo1IicWJUw+5YE0HLXLX9dD9PPFOzT3Pju8Zr+iQztEYgAvJqdDalQmQPxZbJkfEJ3hH4atI8tji3n4mCn5AyPM6xuLGbMgjCzhfyqX3Y9ZbPnk/yYHsb24vwfk,iv:ilXryTyuyKWjJE7T42nRN1nNkWrJwsYnHq95YuLlAo0=,tag:C/uphZ+6Rf/axuAdKjednw==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK25XOGU1SmF5bXVLTERQ
            UndINHJ4enR1b1NRM2ErSEFocXZsZ2ROS213ClVlQWJkaUVVeGd1WDVQUlB2NWdu
            V0ZndTRQLzdsOXpTZlpZK2FTb0dOTE0KLS0tIE5jTTlNdXBjWXNiK20wS3dWWnlU
            MkVNVXZiaUQ4MFc2TGVleHBZb25UTzQK9/bpVUADxn3n2lpsG1ty9L0IGMqx9mbK
            fJEpsmyCyRoTmtlswr4nkK+t/SZF6Vmn49GSO5qYpXzNwtuTm10ekA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T05:38:37Z"
    mac: ENC[AES256_GCM,data:BbKjV3v99VPC7m4v+mAjHMR+IYy/y47tVxzBRvcjvYVu1NVZzgt7fbUwowWCg0ort86rY5qpX1JvYFxOdXSf/hUV4j7pYfqjI2UzPN/Pwmiw+9iOfoFD7YAeVdlgSyRKztPytDtkEQLB3U8CDYM/qRoqh103x6wSFdOwPWzIKKw=,iv:ormYqoDuizAJgD/t0B1akua9B//nYIKpTSVBO1yTgFU=,tag:O3/M8q3br6VzprHEYBhgeg==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
