apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:q6T5CarZ30eyyOuK4fjQrKl+lt5SwAofA0d6WOYiCC8=,iv:1Y6WNBpfQJwy3230SOcdZNLIPB5kF7VNsptv59/0gOo=,tag:+kXcXOEyR7iLLxs1TT6QkA==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTnhOSlNUS1FEQWFnY3Zn
            R2l6ejcvVDZqY1NEc2tjamVSRXZvQzZaUW5FClNYYkQ4a01mYXo4ZzdHd29VK0Vx
            V3ZFakNScmtDa0xoek5sc2RIWHlkUEUKLS0tIC85aEtjalcwR0l2d3I3M21KK2JB
            dHBrbDhyUHcrOW1HWlNJKzBpYWVVN28K9T9N2taP5Yk5Chdh33TqtnyUi6FQoA+o
            AhWr60YNoy7AVGPxFS9JWM1FkLe35nNjrf1TKYnMIdiSuksFaeWv0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T06:05:06Z"
    mac: ENC[AES256_GCM,data:jYdEhdspNPKfwo7QodRafxwKK8zmGEiBikQjI2sGQ8Ij84zmmcMDOyKe0r/ysMsEshEPwGCr8JJd5QS/9XeceYjuPL4cCALL3UdGeLzBxg/sQxfLIuhbu7BGwqquh40Irn4KYFk+A1yoXJ4pgsAsyvR2TexaZ2mZSlAMc6EAHHA=,iv:pUIDfURjIOnBvrbJlWw+vWH6ExMixOW97zc8Cvu0ZD4=,tag:y21lXmnE8bkXKk6ga+Gx+A==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
