apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:J7XdF6rBAJWbCJf+Sq2WxMUxitKX+/PyKjxLb7CfQoavDQK7+EbNrjaXk0IxcmA1GGFVxc/0kyt248brVoVBr1tsyEPajDakVLhmbIcev1cpzv1tQFUtyejlu+brWuoYAt+wQe8RxF5MIqW4YZcoaNx7oK/eHDqnOK40p45muoFrkGvwpdFd5AcebSdWM5ioh0VWPto8IRNjDxeHZedAbaAp16/pOLxuiDvR+FH8b59HoC/bFkXN1g==,iv:dtyqLlstbfC8ei5EdtgzQgs7p6d4MN01rpgAbXntv24=,tag:mzuJorDVl+zN2++g+v0Kpw==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0LzVxdjBqRmZaOW5ZTnJj
            R1Y2c2llaVF4a0JxZlVxL3NUZnZvcWczM3dFClhjcEs0bTRwTkM2RTZBMlJxUDFB
            NmFFTHpXbkcrdnBnYnd6dnhtMUQ0eEEKLS0tIHBZaTJYdjhsSTdNcXJ1NktqUWV1
            Nm9mejR3dS9ucmtRYmYrY3JUMU1BWEkK1FX7nVBk0DQfQwnWKv99ge7se0ZScjAp
            WjRfqT+wI5SekN8WRCafxXaSwxXezcTt1sqLzK1lONhgWSH/HNxoLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T05:16:52Z"
    mac: ENC[AES256_GCM,data:TsjdxL3SamK+IRDIzAndrr9Oo1HhQ2bFzRnnmbFpo0953KnVsTA0IAtA/s/J971cAo/hFbd2h8y1NTY4s44ilXfroGfrYvSkICT6mDiAO6fMRlWEs9sgClZq4/Pbxiba7iALFqoIpUjwayWs9x0xKxplWMFOQoUIzDbRLwIV8PE=,iv:QcTWdIRxdOckPw9ElxPoSRITiYKOesX/5+yHlHOcOeY=,tag:wW5PlLBz1pd72nsRHQ5FEA==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
