apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:i7gzSzDcp2tyvztSTrXW9CkdbFuP2TeRfbIM2UqNIgHRPWejzRysS35LHzrxDRAc784V5qhMpgKsb32r11S6ttNje48M71bF8gpfRL4z9GyuPHfrZwFDaU1d6JXQkGG7Aeei2sEsT7Rfn+mzRH39l6vD4PAUwRKuO7xLHiiwcdBDlHo04ZB1ODjmVWxRYf2UZQ063SUMZ79VZXx26ZTlcsZy5Lg64NbPNNRChOCc9cVTWKhqunRnb3vAxlKT2Fn37AceXQ1BOLhwZBN1yq2QhwHXRzOWE5Q=,iv:mqTnwCdnbwCw9u3ysCi3UsvFUzxB+Q0aJndegPO/AV0=,tag:AwqchFrdh0dDc5w5Ab5tLA==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0LzVxdjBqRmZaOW5ZTnJj
            R1Y2c2llaVF4a0JxZlVxL3NUZnZvcWczM3dFClhjcEs0bTRwTkM2RTZBMlJxUDFB
            NmFFTHpXbkcrdnBnYnd6dnhtMUQ0eEEKLS0tIHBZaTJYdjhsSTdNcXJ1NktqUWV1
            Nm9mejR3dS9ucmtRYmYrY3JUMU1BWEkK1FX7nVBk0DQfQwnWKv99ge7se0ZScjAp
            WjRfqT+wI5SekN8WRCafxXaSwxXezcTt1sqLzK1lONhgWSH/HNxoLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T07:27:56Z"
    mac: ENC[AES256_GCM,data:1iXUl7ddm9MSU3hCjeEX6gxWmKawmxI/D2SDYHmCP887rucuKlZiFWiTD7yHVEc3lzPXSfIwV76O+qBFAty9wKFffAjhxDDbdBNYcQobyTtbQfPBWuZk1T0m4UXMGZyxaSUm7pfhn6MNOXZ6oaehQTW+LU5IxbyCH03fKq2YPqg=,iv:bGdUf08//2jhEgKihfKgUs1Pv218jweQWJXUcXlki7s=,tag:7Rx8c4wAdb2JDcAzpjj+MQ==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
