apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: paperless-postgres-secret
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: database
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    username: ENC[AES256_GCM,data:FZzIQnPMWBR/,iv:4LRQqqDumXqtcsnyMBMedSYFIXHm4ewrYAJXJIVFeW4=,tag:deysvMPKsAn6yF17MHrfQg==,type:str]
    password: ENC[AES256_GCM,data:rsYSlTB3DAfe08xqmRM0LnaXNsoBhyr66YMPsRJaLDwsDr54UQvfbx3P+8GMvpdhBRqn6BWI9NE1lJy5ulrygg==,iv:VYMTYXLHmTarfk7cc3lsbCA5HLjm9UIE3J+wka0MsRA=,tag:4X+kdYjLXEvQEDc6xHdJPQ==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNm9TUHo2VEUzSzk3eWFi
            RGZBbm5XR3BiWDY1UlpSRUtBNG9IVmJ2QVVVCmFEcUNERFVtRDRlOEFSdzRPcTFK
            MFg0SW5oNk5tQkxrVDhxV3RiTjFJWDgKLS0tIFI1TjQ2Tnp3azRaZHdaMERzZWhu
            WlBQVnZxYlFoNFBJSE1NVnMvTTV5M0kKOaHUHuKkDuLrIVCvEfppw8P3nyhsIRiR
            JCZlsSKRn8qJeIj5ASwzP09ozIgJc9fSccQxjiesI+ozRfrHEHFtiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T04:57:00Z"
    mac: ENC[AES256_GCM,data:saBH9KGwf1ztQFCOFRQ/rLdqGFpyClTNFpK/6cNIA+7JHpl2O91j5aYduDjCsKaOoMXBXDpARv2WCRjSNpzxpQPEd/v2GAk+k2QectXCCA0VwqrWIIpPysEMmvLP3z3nx9qmqQEwoPuvMxSMaZSTMHcbFnp8GtEBKLgdM28Opgs=,iv:5t2ljxXsbxqQuL/t3kgyGo8mJkPYghd1f93LniHKUbE=,tag:Z22AQ1RFotyKS5R8XJszAg==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:C/kFUg5Q4pYpmS/DiKKiM2AxZ9cwpD/e3C400PCbYbOiInEIXgMKZZSw0Hy8OciKxyzwXiRj7oXMDRtN+4TZ9w==,iv:2KIyvCJx2wHoXVl9aq8JJ75bcESSfYp6ftWmtiZ7mTE=,tag:WR2eBqtMwKVRISbmkaPomA==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:Mw5BRC0=,iv:lvnL9h/adVrH6kMMEA5CBDiK2mvxo1y3KO7ZHS+cMAQ=,tag:0iFQ9xa7VpBMGftigkOiQw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:IGPNwtzYZIlbvIfNOzSF/xnbw1A=,iv:31aj1Crk0QBKTUzEO6nGMPqg50OXgO9ayUSQ3E5Zly4=,tag:9Ume6B0yLGMesyahsxnDHw==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNm9TUHo2VEUzSzk3eWFi
            RGZBbm5XR3BiWDY1UlpSRUtBNG9IVmJ2QVVVCmFEcUNERFVtRDRlOEFSdzRPcTFK
            MFg0SW5oNk5tQkxrVDhxV3RiTjFJWDgKLS0tIFI1TjQ2Tnp3azRaZHdaMERzZWhu
            WlBQVnZxYlFoNFBJSE1NVnMvTTV5M0kKOaHUHuKkDuLrIVCvEfppw8P3nyhsIRiR
            JCZlsSKRn8qJeIj5ASwzP09ozIgJc9fSccQxjiesI+ozRfrHEHFtiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T04:57:00Z"
    mac: ENC[AES256_GCM,data:saBH9KGwf1ztQFCOFRQ/rLdqGFpyClTNFpK/6cNIA+7JHpl2O91j5aYduDjCsKaOoMXBXDpARv2WCRjSNpzxpQPEd/v2GAk+k2QectXCCA0VwqrWIIpPysEMmvLP3z3nx9qmqQEwoPuvMxSMaZSTMHcbFnp8GtEBKLgdM28Opgs=,iv:5t2ljxXsbxqQuL/t3kgyGo8mJkPYghd1f93LniHKUbE=,tag:Z22AQ1RFotyKS5R8XJszAg==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
