apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:VmgB/P7JkEMbsmg31UCgPwRLPQB5drr+X0XoT3FtqkPz0zdQDua2aA==,iv:Mzzax0C9D93+v+zr5ezfwCV42y8WnL8WjBjB61SjN5I=,tag:IqE8WweDG77YJpgassQI6g==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQXVzOCtXVDRIOTZ2NGVz
            VnhlQnlxVjdVVk9yYzJqNGVEYXpTOThCb1QwCnA5V0ZKWlM3SmlwWkxORHRwOWJI
            L0YyblZJQXBqaHNMVFZyUlBqUDVSZDQKLS0tIE9HYXpsTzJXdmJmU0NIdXpxamVN
            bmhRLzdUUTdvSy81RERjWERvUWxRS00KqXyG+PvPNt2ctCvduPiON1QWDF7vAiNO
            9Yurqv4BSB0V1ylbLNguWw/vhB5QVDSc1US6np7hMNgNF2RHRRoHaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T00:20:24Z"
    mac: ENC[AES256_GCM,data:5oXWy+x0ceOd5J6veW3AF5JU0EXP0ur3EsAZwiNGHjHSeDhRxrTf5V9PxaYP1tWEpyr9dfixBvtGoaHPsF3M+90uGn+Y2W/+mev4xqBbQq4OlLFK04/2rJMZRSCa6x/AcL5Gf307+GIGOXycS+NLicoUwr/ejrMAYXOtbH04LgI=,iv:DDxs52wwTxddjtlvw447Fw5SILuJzSKB706LJ1MXBX8=,tag:1U/9cFxen+inS7CTrA/jYA==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
