---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-operator
spec:
  dependsOn:
    - name: openebs
      namespace: openebs-system
  interval: 1h
  path: ./kubernetes/apps/database/cloudnative-pg/operator
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-cluster
spec:
  dependsOn:
    - name: cnpg-operator
  interval: 1h
  path: ./kubernetes/apps/database/cloudnative-pg/cluster
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-databases
spec:
  dependsOn:
    - name: cnpg-cluster
  interval: 1h
  path: ./kubernetes/apps/database/cloudnative-pg/databases
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plugin-barman-cloud
spec:
  dependsOn:
    - name: cnpg-operator
  interval: 1h
  path: ./kubernetes/apps/database/cloudnative-pg/plugin-barman-cloud
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
