apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:iSi86w+/9aRGG0M0RlZrM/r5NIDLRUWiVFFOdXYvG6UfGjc8mrZnHQzYuRI=,iv:9woDKkQBstSZZR/lfkKoY5VERbRXvtXDW6JdRq8Oa5E=,tag:sM4I6jWuHVODo4xDMRkySQ==,type:str]
sops:
    age:
        - recipient: age1pw3ushyk74yquev7sc7wu0sw6sfku0nfswpqua8ljm0e8vmpxsjslmgv75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eWdsS2FlaStSZ3FiMExm
            d240citwZ0x6dFNDVlBKUG5YT1M2MXNLWlRNCmlkcUVIMkZvSTZwZUZObWxESFNz
            c0VzRHhra0d4RnFVNmxGTGNNTlhpQk0KLS0tIEh4OThVU1cwQVJFTm9ORDYvMXZL
            cTdrOTBTZUdPUkF2NWxMRFdHOWhLMXcKntK4DJlexxLmXpOm72Mscd2mV7ZWAWIQ
            LaZfMcB4keDCoInzgk5ACx+XbU2Hqsz24nH88CQZfTfZHye1KSbtuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T07:51:15Z"
    mac: ENC[AES256_GCM,data:B9bLK2+lxv90bFny6WXLiKsbeG6+m2U3E5skEt98pYUmcT97bd0jO2l5jwSme+8EfQ2jIvN4G7tVjNBKoCKu0KwHMEVCPgFW/dRwYqeS0w1B0Mc0CPLX0F6Ka64CBat1B2XnGHmSPmlngLg+XhDgEpTudCxFIVrBrwEAhQeP4lA=,iv:6jSX8UhgZtHtb88agXZk9+0q637kv4qbWYRcqNiIKYM=,tag:OqA6HWf1sV15hBMzznv+XQ==,type:str]
    encrypted_regex: ^(data|stringData|crt|key|token|bootstraptoken|secretboxencryptionsecret|secret|id)$
    mac_only_encrypted: true
    version: 3.11.0
