---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless
spec:
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: paperless-valkey
  interval: 1h
  path: ./kubernetes/apps/documents/paperless/app
  components:
    - ../../../../components/volsync
    # todo
    # - ../../../../components/database
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_UID: "1000"
      VOLSYNC_GID: "1000"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: documents
  wait: false
