apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  poolname: "tank"
  fstype: "zfs"
  recordsize: "128k"
  compression: "on"
  dedup: "off"
  shared: "yes"
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
